### ISSUE TITLE
Render quoted code block in live preview mode

### ISSUE THREAD

**Issue by jyrodgers** [nickmilo/LYT-Mode#22]
Hello again,

In live preview mode please render a code block that is quoted in the same way as in-line code.

Here is some example content

```
>Some quoted text
>`in-line code`
>Some additional quoted text


>Some quoted text
>```
>code block
>```
>Some additional quoted text
```

Here is how it is rendered in live preview mode 

![CleanShot 2022-02-10 at 12 19 30](https://user-images.githubusercontent.com/4572538/153489837-b416ca55-03a3-4198-9bef-d41bb7627224.png)

I have updated to the most recent version.

**Comment by ceciliamay** [comment]
Hello there!! Thank you so much for posting this issue!! Unfortunately Obsidian in Live Preview Mode doesn't identify the codeblock in quote format as you've shown as a codeblock. Obsidian still sees it as a quoteblock. 
![image](https://user-images.githubusercontent.com/90643719/153507078-bc25664a-177c-42c3-b671-0fc4fe972ac6.png)
Because of this, I can't style it to become a codeblock 😓 For some reason Obsidian previews it as a codeblock though!
![image](https://user-images.githubusercontent.com/90643719/153507243-2b8facff-6fee-4a1d-9ba4-afa0affb4815.png)
I would recommend posting this as a feature-request/bug report to the Obsidian forums instead! 😄
