### ISSUE TITLE
Header text shows unpredictably while typing

### ISSUE THREAD

**Issue by nickmilo** [nickmilo/LYT-Mode#8]
https://twitter.com/JimGrange/status/1484062473527476225

**Comment by jetfighter82** [comment]
Same issue here. It’s happening on iOS for me. Screenshots show reading mode and editing mode of the same note.

### Reading mode, no issues
![188F82B3-6F7C-4AF7-823C-D342AE4EE529](https://user-images.githubusercontent.com/1951708/150629188-53a821f2-eeaa-4d90-8e46-2c0a4be02f7e.png)

### Editing mode is where things go wonky
![E5551961-28C1-4EEC-88F6-C2840E5F2656](https://user-images.githubusercontent.com/1951708/150629191-f95dd3fe-6a9d-48ba-8eb1-728b4d59572e.png)

**Comment by shankarnakai** [comment]
I had exactly the same issue. What I could observer is that the header disappear when the word is not recognized by `Obsidian`.

The header styles that are trying to apply gradient are conflicting with the `spell error` class for the words `.CodeMirror .cm-spell-error`

The way that I solve was removing the `css` that was adding gradient to the H1 and keep a single color.

Example:
```diff
 .cm-header-1,
 .markdown-preview-view h1,
 .markdown-preview-view h1 code {
-    background: var(--color-yellow-gradient-1);
-    -webkit-background-clip: text;
-    -webkit-text-fill-color: transparent;
+    color: var(--color-yellow);
     filter: drop-shadow(var(--header-shadow-size) var(--header-shadow-color));
 }
```

**Comment by shankarnakai** [comment]
I create a PR with my approach: https://github.com/nickmilo/LYT-Mode/pull/12

**Comment by ceciliamay** [comment]
Hello everyone! Cecil here, developer of LYT Mode 🔦!

I'd like to confirm if all of you are using the Legacy Editor when this happens? @shankarnakai and @jetfighter82 ?

**Comment by jetfighter82** [comment]
Hi @ceciliamay I am not using the Legacy Editor.

**Comment by shankarnakai** [comment]
oh yeah, I'm using the legacy editor

**Comment by shankarnakai** [comment]
@ceciliamay Any updates?

**Comment by ceciliamay** [comment]
Currently working on deliverying best of both worlds and collaborating on this with Nick - will try shipping a solution by early next week! 😄 @shankarnakai

**Comment by shankarnakai** [comment]
Thank you so much. Let me know if I can help with anything. Excited to use this theme 🙌

**Comment by ceciliamay** [comment]
As @shankarnakai has mentioned, this issue occurs due to a conflict with the spell checker. But, it seems that this issue only occurs on iOS devices. I've tried replicating it with my Android devices and everything is fine!

We still want you to experience the beautiful gradient headers LYT initially offers, so we're continuously looking for a more elegant solution to this issue. For now,[ as with v.1.1 update](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0), we are offering a **"Safe Style" Option** through the Style Settings Plugin, which should fix any visual bugs you experience with Headers and Highlights. We highly recommend downloading the plugin for the best experience!

![image](https://user-images.githubusercontent.com/90643719/152687058-fc476984-9464-492d-a64c-04a2706ca406.png)

You can read more about the [update over here](https://github.com/nickmilo/LYT-Mode/releases/tag/v.1.1.0)! Please update your themes, and thank you all for posting this issue!
